layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.375
  brandStrength: 0.7867383
  lightness: 0.9375
  brandColors:
    - '#A4B4BC'
    - '#272731'
    - '#776D66'
    - '#436D5C'
    - '#9A5D38'
  rhythmicContrast: 0.9880663042422384
typography_spectrum: 0.80416
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thisisjamesj
